Flight planner Api iteration 1
KrEdu/FlightPlannerAPI pull request #1
Opened 2021-09-21 18:12 UTC by KrEdu

All tests passed

2021-09-23 19:36 UTC, ausmoons requested changes
![image](https://user-images.githubusercontent.com/53189160/134572327-4a473448-4312-4411-8e8b-2faf043a6e3c.png)
Es nevaru palaist tavu projektu, jo nav .sln faila

2021-09-23 19:36 UTC, ausmoons commented on Models/Airport.cs
> +        //public int Id { get; set; }
Lieks komentārs

2021-09-23 19:36 UTC, ausmoons commented on Models/Airport.cs
> +                || airport.ToLower().Contains(phrase.ToLower().Trim()))
return uzreiz

2021-09-23 19:36 UTC, ausmoons commented on Models/AirportValidate.cs
> +                String.IsNullOrEmpty(airport1.airport) || String.IsNullOrEmpty(airport2.airport))
False var apvienot vienā un tad var vispār uzreiz return

2021-09-23 19:36 UTC, ausmoons commented on Models/FlightValidate.cs
> +            else if (DateTime.Parse(flight.DepartureTime) > DateTime.Parse(flight.ArrivalTime) ||
Var būt viens liels returns

2021-09-25 06:43 UTC, ausmoons requested changes
![image](https://user-images.githubusercontent.com/53189160/134761693-68ca058d-5bfe-4deb-af69-ca2057d8c10b.png)
 Pamēģini pats noklonēt repo un palais projektu

2021-09-25 09:53 UTC, KrEdu commented
Sorry about the multiple commits :). Had to edit files through GitHub because I'm almost finished with the 2nd iteration and didn't want to deal with merge conflicts,  at least for now.

2021-09-26 12:01 UTC, EdgarsSalmins commented on Controllers/AdminController.cs
> +                else return Conflict();
te else nav obligāts. :)

2021-09-26 12:01 UTC, EdgarsSalmins commented on Controllers/CustomerController.cs
> +            else
te arī else nav obligāts. :) ja if neizpildīsies vienmēr jānotiek šai darbībai. :)

2021-09-26 12:02 UTC, EdgarsSalmins commented on Models/Airport.cs
> +                || airport.ToLower().Contains(phrase.ToLower().Trim()))
šo arī varētu izlabot. :)

2021-09-26 12:03 UTC, EdgarsSalmins commented on Models/AirportValidate.cs
> +                String.IsNullOrEmpty(airport1.airport) || String.IsNullOrEmpty(airport2.airport))
te vajadzētu lasāmību uzlabot. :)

2021-09-26 12:04 UTC, EdgarsSalmins commented on Models/AirportValidate.cs
> +            else if (airport1.airport.ToLower().Trim() == airport2.airport.ToLower().Trim())
šo izteiksmi var iznest metodē kas atgriež vai lidostas sakrīt. :) 
FlightAirportsMatch tad ifs būs vieglāk uztverams

2021-09-26 12:04 UTC, EdgarsSalmins commented on Models/AirportValidate.cs
> +                String.IsNullOrEmpty(airport1.airport) || String.IsNullOrEmpty(airport2.airport))
te var iznest metodē un nosaukt AirportHasValidValues

2021-09-26 12:05 UTC, EdgarsSalmins commented on Models/FlightValidate.cs
> +                    && !String.IsNullOrEmpty(flight.Carrier) && !String.IsNullOrEmpty(flight.DepartureTime)
FlightHasValidValues ? un tad datumu pareizību zem tā pārbaudīt?

2021-09-26 12:08 UTC, EdgarsSalmins approved these changes
vienmēr kad raksti nosacījumus par validāciju šajā gadījumā.. padomā lai to kodu varētu izlasīt arī neko nesaprotot no koda. :) 
piemēram if(FlightHasInvalidValues()) return BadRequest()
šāds kods ir ļoti labs jo ir viegli lasāms un uztverams.. un ja vien mani neinteresē kas ir Invalid/Wrong values pie flight es varu tur nemaz neskatīties uz detaļām. 
mērķis ir panākt lai kods ir lasāms kā vienkārša grāmata.

2021-09-26 12:40 UTC, merged